spring:
  datasource:
    url: "jdbc:sqlite:/D:\\Projects\\Chess-Agent\\src\\main\\resources\\company.db"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.hitech.Chess.Agent.SQLiteDialect




